package Threads;

import Logic.Ant;
import Utils.Settings;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.List;

/**
 * Evaluates rules supplied to constructor and saves result as image.
 */
public class AntRunnable implements Runnable {

    private final List<String> rules;

    public AntRunnable(List<String> rules) {
        this.rules = rules;
    }

    @Override
    public void run() {
        for (String rule : rules) {
            saveImageWithoutPanel(rule);
        }
    }

    /**
     * Saves image generated by ant running given rule. Creates image from grid and saves it directly into file.
     *
     * @param rule that ant is running
     */
    private void saveImageWithoutPanel(String rule) {
        System.out.println(Thread.currentThread().getName() + " working on: " + rule);

        Ant ant = new Ant(Settings.SIZE_IN_PIXELS / Settings.SIZE_OF_SQUARE, Settings.MAX_MOVES, rule);
        ant.allMoves();
        BufferedImage bImg = new BufferedImage(Settings.SIZE_IN_PIXELS, Settings.SIZE_IN_PIXELS, BufferedImage.TYPE_INT_RGB);
        ant.draw(bImg.createGraphics());

        try {
            ImageIO.write(bImg, "png", new File(String.format(Settings.BASE_PATH + "/%d/%s.png", rule.length(), rule)));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
