package Logic;

/**
 * Calculates how interesting grid generated by {@link Ant} is.
 */
public class InterestingnessEvaluator {
    private final int[][] grid;
    private final int dimension;

    public InterestingnessEvaluator(int[][] grid) {
        this.grid = grid;
        dimension = grid.length;
    }

    public double horizontalLineEvaluator(int line) {
        double currentLineLength = 0;
        int startIndex = 0;
        int startSameValue = grid[line][0];
        for (int i = 0; i < dimension; i++) {
            if (grid[line][i] == -1 || grid[line][i] != startSameValue || (i == dimension - 1)) {
                // we subtract 1 because we want to give 0 score to line of length 1;
                int lengthAdjusted = ((i - startIndex - 1) == -1) ? 0 : i - startIndex - 1;
                currentLineLength += (Math.pow(lengthAdjusted, 2) * 0.1);
                startIndex = i;
                startSameValue = grid[line][i];
            }
        }
        return currentLineLength;
    }

    public double evaluateAllHorizontalLines(){
        double result = 0;
        for (int line = 0; line < dimension; line++){
            result += horizontalLineEvaluator(line);
        }
        return result;
    }
}
