package Graphic;

import Logic.Ant;
import Logic.RulesGenerator;
import Utils.Settings;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

public class ImageGenerator {
    private Ant ant;

    /**
     * Cycles through all rules of length Settings.RULES_LENGTH and saves images into file.
     */
    public void drawAllRules() {
        RulesGenerator rulesGenerator = new RulesGenerator(Settings.RULES_LENGTH);
        while (rulesGenerator.hasNext()) {
            String rule = rulesGenerator.next();
            System.out.println("working on: " + rule);
            ant = new Ant(rule);
            saveImageWithoutPanel(rule);
        }
    }

    /**
     * Saves image generated by ant running given rule. Creates image from grid and saves it directly into file.
     *
     * @param rule that ant is running
     */
    private void saveImageWithoutPanel(String rule) {
        ant.allMoves();
        BufferedImage bImg = new BufferedImage(Settings.SIZE_IN_PIXELS, Settings.SIZE_IN_PIXELS, BufferedImage.TYPE_INT_RGB);
        AntGraphic antGraphic = new AntGraphic(ant);
        antGraphic.drawImage(bImg.createGraphics());

        try {
            ImageIO.write(bImg, "png", new File(String.format(Settings.IMAGE_BASE_PATH + "/%d/%s.png", rule.length(), rule)));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
